#!/usr/bin/env bash
# Bash script that installs a Nginx on a new ubuntu machine
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
service nginx restart
