#!/usr/bin/env bash
# Script that displays numbers 1-20 and echos messages on certain lines

i=1
while [ $i -le 20 ]; do
	if [ $i -eq 4 ]; then
		echo $i
		echo "bad luck from China"
	elif [ $i -eq 9 ]; then
		echo $i
		echo "bad luck from Japan"
	elif [ $i -eq 17 ]; then
		echo $i
		echo "bad luck from Italy"
	else
		echo $i
	fi
	(( i=i+1 ))
done
