#!/usr/bin/env bash

#a Bash script that configures an Ubuntu server
cp /etc/hosts etc/hosts.tmp
sed -i -e "s/127.0.0.1/127.0.0.2/g" "/etc/hosts.tmp"
echo "8.8.8.8 facebook.com" >> "/etc/hosts.tmp"
cp etc/hosts.tmp etc/hosts
